name: React CI

on:
 push:
  branches:
    - "master"

jobs:
  build:
     run-on: ubuntu-latest
     strategy:
       matrix:
        node-version: [15.x]

     steps:
      - user: pankaj9901
      - run: npm install
      - run: npm run build
      - run: npm test      